# Streamlit Secrets Configuration
# Add your RapidAPI key here
RAPIDAPI_KEY = "e941ea6c90mshc41fafdd3f5f2ccp1afb16jsnaeab51486f9e"

# MySQL Database Configuration
[mysql]
host = "localhost"
user = "root"
password = "Vasu@76652"
database = "cricketdb"
