# Streamlit Secrets Configuration
# Add your RapidAPI key here
RAPIDAPI_KEY = "6e351d1cbcmshd1677dcbcb6cb91p11ec94jsn5289c5d22065"

# MySQL Database Configuration
[mysql]
host = "localhost"
user = "root"
password = "Vasu@76652"
database = "cricketdb"
